version: "3.8"

services:
  mysql-upb-master:
    image: mysql:8.0
    container_name: mysql-upb-master
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: upbgeneraladmin
      MYSQL_DATABASE: upb
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: super_secure_replication_password
    ports:
      - 3310:3306
    networks:
      - upbnetwork
    volumes:
      - ./mysql/dump_upb.sql:/docker-entrypoint-initdb.d/dump_upb.sql

  mysql-lpz:
    image: mysql:8.0
    container_name: mysql-lpz
    depends_on:
      - mysql-upb-master
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: upblpzadmin
      MYSQL_DATABASE: upb
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: super_secure_replication_password
    ports:
      - 3307:3306
    networks:
      - upbnetwork

  mysql-cbba:
    image: mysql:8.0
    container_name: mysql-cbba
    depends_on:
      - mysql-upb-master
    command: --server-id=3 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: upbcbbaadmin
      MYSQL_DATABASE: upb
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: super_secure_replication_password
    ports:
      - 3308:3306
    networks:
      - upbnetwork

  mysql-scz:
    image: mysql:8.0
    container_name: mysql-scz
    depends_on:
      - mysql-upb-master
    command: --server-id=4 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: upbsczadmin
      MYSQL_DATABASE: upb
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: super_secure_replication_password
    ports:
      - 3309:3306
    networks:
      - upbnetwork

  mongo-service:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: mongo-service
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: upb
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongo-data:/mongo-data
      - ./mongo/config/mongod.conf:/etc/mongod.conf
      - ./mongo/config/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js
    networks:
      - upbnetwork

volumes:
  mysql_master_data:
  mysql_lpz_data:
  mysql_cbba_data:
  mysql_scz_data:
  mongo_data:

networks:
  upbnetwork:
    driver: bridge
